name: Release Plugin

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      # Configure Gradle for optimal use in GitHub Actions, including caching of downloaded dependencies.
      # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

      - name: Build with Gradle Wrapper
        run: |
          chmod +x gradlew
          ./gradlew build --stacktrace

      - name: Release plugin
        id: create-release
        uses: actions/create-release@v1.1.4
        with:
          release_name: Release ${{ github.ref }}
          tag_name: ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload release asset
        uses: actions/upload-release-asset@v1.0.2
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: build/libs/*.jar
          asset_name: ExcludeAccess.jar
          asset_content_type: application/java-archive
